-- ============================================================================
--  SOUTARAH — SUPPRESSION DES VEHICULES HORS FLOTTE OFFICIELLE
--  Généré le 2026-10-01
--
--  Les véhicules listés ci-dessous ne font PAS partie de la flotte validée
--  par le client : ils sont SUPPRIMÉS de la base.
--
--  Les autocars de 25 et 32 places sont volontairement conservés.
--
--  ⚠️ Les clés étrangères sont en RESTRICT sur articles_panier et reservations :
--  l'ordre des opérations ci-dessous est impératif. Un véhicule portant une
--  réservation n'est jamais supprimé (historique commercial) — il est seulement
--  neutralisé, ce qui le retire du site et de l'application.
--
--  Méthode recommandée : node server/scripts/clean-vehicle-catalog.cjs --restore
--
--  Import :  mysql -u <user> -p <base> < ce fichier
-- ============================================================================

SET NAMES utf8mb4;

-- 1. Lignes de panier portant un véhicule retiré (contrainte RESTRICT).
DELETE `articles_panier`
WHERE `vehicule_id` IN (
  SELECT `id` FROM (
    SELECT `id` FROM `vehicules`
    WHERE (`marque`, `modele`) IN (
  ('Toyota', 'Highlander'),
  ('Volvo', '9700'),
  ('Renault', 'Latitude'),
  ('MG', '3'),
  ('Renault', 'Kardian'),
  ('Geely', 'Cityray'),
  ('Peugeot', '108'),
  ('Soueast', 'Soueast S06'),
  ('BYD', 'Song PLUS NEV'),
  ('Fiat', 'Panda'),
  ('Hyundai', 'i20'),
  ('Dacia', 'Jogger'),
  ('Soueast', 'S09'),
  ('Dacia', 'Sandero Stepway'),
  ('Mercedes-Benz', 'GLE'),
  ('Soueast', 'S05'),
  ('Peugeot', '207'),
  ('Opel', 'Corsa'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Proace'),
  ('Citroën', 'Elysée'),
  ('Citroën', 'C4'),
  ('Audi', 'A6'),
  ('Audi', 'Q5'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Elantra'),
  ('Opel', 'Adam'),
  ('Opel', 'Astra'),
  ('Opel', 'Crossland'),
  ('Opel', 'Mokka'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Wrangler'),
  ('Fiat', '500'),
  ('Fiat', '500X'),
  ('Fiat', 'Egea'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Tipo'),
  ('Nissan', 'Qashqai'),
  ('Mercedes-Benz', 'Classe A'),
  ('Mercedes-Benz', 'Classe E'),
  ('Mercedes-Benz', 'Vito'),
  ('SEAT', 'Arona'),
  ('SEAT', 'Leon'),
  ('Chevrolet', 'Spin'),
  ('MG', '5'),
  ('MG', 'HS'),
  ('MG', 'ZS'),
  ('Renault', 'Clio'),
  ('Renault', 'Logan'),
  ('Renault', 'Arkana'),
  ('Renault', 'Captur'),
  ('Renault', 'Mégane'),
  ('Renault', 'Trafic'),
  ('Changan', 'CS35'),
  ('Dacia', 'Sandero'),
  ('Dacia', 'Logan'),
  ('Dacia', 'Logan MCV'),
  ('BMW', 'Série 5'),
  ('BMW', 'X2'),
  ('Cupra', 'Leon'),
  ('Kia', 'Ceed'),
  ('Kia', 'Forte'),
  ('Kia', 'Sportage'),
  ('Kia', 'Sorento'),
  ('Kia', 'Carens'),
  ('Peugeot', '208'),
  ('Peugeot', '2008'),
  ('Peugeot', '3008'),
  ('Peugeot', '301'),
  ('Peugeot', '308'),
  ('Ford', 'Focus'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'T-Roc'),
  ('Skoda', 'Citigo'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Octavia'),
  ('Changan', 'Yuexiang'),
  ('Skoda', 'Superb'),
  ('Dacia', 'Lodgy'),
  ('Geely', 'Emgrand'),
  ('Honda', 'Civic'),
  ('Peugeot', '408'),
  ('Kia', 'K5'),
  ('Kia', 'Carnival'),
  ('Hyundai', 'i30'),
  ('Land', 'Rover Range Rover Evoque'),
  ('Alfa', 'Romeo 159'),
  ('Opel', 'Crossland X'),
  ('Jeep', 'Avenger'),
  ('Mitsubishi', 'Nativa'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Starlet'),
  ('Citroën', 'Picasso'),
  ('Hyundai', 'Getz'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Optra'),
  ('Cadillac', 'STS'),
  ('Citroën', 'C3'),
  ('Nissan', 'Sentra E-Power'),
  ('Trumpchi', 'Emkoo'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Denza', 'D9'),
  ('Exeed', 'Zhuifeng'),
  ('GAC', 'Trumpchi M6'),
  ('Trumpchi', 'GS4'),
  ('Land', 'Rover Range Rover Sport'),
  ('Ford', 'Edge'),
  ('Nissan', 'Xterra'),
  ('Audi', 'R8'),
  ('Volkswagen', 'Polo'),
  ('Porsche', '718 Boxster'),
  ('Rolls-Royce', 'Dawn'),
  ('Chery', 'Omoda'),
  ('Jetour', 'Dasheng'),
  ('Kia', 'K3'),
  ('Toyota', 'LEVIN'),
  ('Trumpchi', 'GS8'),
  ('Tesla', 'Model Y'),
  ('Porsche', 'Cayenne'),
  ('BMW', 'Série 4'),
  ('Porsche', 'Macan'),
  ('Toyota', '4Runner'),
  ('Ford', 'Galaxy'),
  ('Hyundai', 'Venue'),
  ('Honda', 'Odyssey'),
  ('Lamborghini', 'Urus'),
  ('Mercedes-Benz', 'CLE'),
  ('MG', 'GT'),
  ('Trumpchi', 'GS3'),
  ('Mitsubishi', 'Attrage'),
  ('Infiniti', 'QX60'),
  ('Haval', 'H6'),
  ('Geely', 'Boyue L'),
  ('Dongfeng', 'M4U-TOUR'),
  ('Ford', 'Mustang'),
  ('Ford', 'Everest'),
  ('Kia', 'Optima'),
  ('Chery', 'Tiggo'),
  ('Infiniti', 'QX50'),
  ('Chery', 'Tiggo 5X'),
  ('Mitsubishi', 'Xpander'),
  ('Kia', 'Pegas'),
  ('Mercedes-Benz', 'GLA'),
  ('Porsche', 'Panamera'),
  ('Lexus', 'RX'),
  ('Porsche', '911'),
  ('MG', 'RX5'),
  ('Nissan', 'Versa'),
  ('GMC', 'Yukon'),
  ('JAC', 'S3'),
  ('Ford', 'Fusion'),
  ('Land', 'Rover Defender'),
  ('Honda', 'Accord'),
  ('BYD', 'Han'),
  ('Chery', 'Tiggo 7'),
  ('Haval', 'Big Dog'),
  ('Hongqi', 'H5'),
  ('Jeep', 'Grand Cherokee L'),
  ('Mitsubishi', 'ASX'),
  ('Audi', 'RS6'),
  ('JAC', 'JS3'),
  ('Mazda', '3'),
  ('Toyota', 'Raize'),
  ('Hyundai', 'Sonata'),
  ('JAC', 'J7'),
  ('Nissan', 'Sentra'),
  ('Toyota', 'Vios'),
  ('Mazda', '6'),
  ('Dongfeng', 'T5 EVO'),
  ('Chevrolet', 'Groove'),
  ('Bentley', 'Bentayga'),
  ('Chevrolet', 'Spark'),
  ('Lamborghini', 'Huracán'),
  ('Toyota', 'C-HR'),
  ('Geely', 'Boyue PRO'),
  ('Trumpchi', 'GN8'),
  ('Trumpchi', 'GA4'),
  ('Kia', 'Cerato'),
  ('Ford', 'Bronco'),
  ('BYD', 'Qin PLUS'),
  ('Livan', 'X6'),
  ('Polestar', '2'),
  ('MINI', 'Cooper Cabriolet'),
  ('Mercedes-Benz', 'CLA AMG'),
  ('Kia', 'Soluto'),
  ('BMW', 'X7'),
  ('Ford', 'Escort'),
  ('Skywell', 'Auto ET5'),
  ('Toyota', 'Avalon'),
  ('Kaiyi', 'X3 Pro'),
  ('Toyota', 'Yaris Ativ'),
  ('ROX', '01'),
  ('Nissan', 'Magnite'),
  ('Lexus', 'ES'),
  ('Toyota', 'Innova'),
  ('Tesla', 'Model 3'),
  ('Volkswagen', 'Jetta'),
  ('Audi', 'Q8'),
  ('Hyundai', 'Creta'),
  ('SAIC', 'MAXUS G50'),
  ('BMW', 'Série 7'),
  ('Dongfeng', 'Venucia V'),
  ('Toyota', 'Veloz'),
  ('Ford', 'Taurus'),
  ('Hyundai', 'Palisade'),
  ('GAC', 'Trumpchi M8'),
  ('Jeep', 'Cherokee'),
  ('Great', 'Wall Tank 300'),
  ('Nissan', 'Maxima'),
  ('MINI', 'Countryman'),
  ('Chery', 'Arrizo 5'),
  ('Nissan', 'Tiida'),
  ('Chevrolet', 'Corvette'),
  ('Mercedes-Benz', 'GLB'),
  ('Rolls-Royce', 'Wraith'),
  ('Hyundai', 'Stargazer'),
  ('Geely', 'EC7'),
  ('BMW', 'M5'),
  ('Nissan', 'Almera'),
  ('Honda', 'City'),
  ('Honda', 'HR-V'),
  ('Volkswagen', 'Teramont'),
  ('Hongqi', 'HS5'),
  ('Mercedes-Benz', 'GLC'),
  ('Volvo', 'XC40'),
  ('Great', 'Wall Tank 500'),
  ('Ford', 'EcoSport'),
  ('Hongqi', 'EHS9'),
  ('Jeep', 'Compass'),
  ('Ford', 'Fiesta'),
  ('Nissan', 'Sylphy'),
  ('AITO', 'M7'),
  ('Mitsubishi', 'Outlander'),
  ('Suzuki', 'Baleno'),
  ('Mercedes-Benz', 'Classe A AMG'),
  ('Geely', 'GX3 Pro'),
  ('Hongqi', 'H9'),
  ('Venucia', 'Grand V DD-i Super Hybride'),
  ('Chery', 'Tiggo 9'),
  ('Jetour', 'T2'),
  ('Nissan', 'Sunny'),
  ('Infiniti', 'Q50'),
  ('Hongqi', 'HS7'),
  ('Mercedes-Benz', 'CLA'),
  ('Chevrolet', 'Aveo'),
  ('BYD', 'Leopard 5'),
  ('Chevrolet', 'Captiva'),
  ('Nissan', 'Altima'),
  ('Geely', 'HaoYue'),
  ('Jietu', 'X70'),
  ('Geely', 'Xingyue L'),
  ('Zhongxing', 'Lingzhu'),
  ('Audi', 'A3'),
  ('Volvo', 'XC60'),
  ('Citroën', 'C5'),
  ('Hyundai', 'Staria'),
  ('Land', 'Rover Vogue'),
  ('Chery', 'Tiggo 8'),
  ('McLaren', '570S'),
  ('Mazda', '5'),
  ('Bentley', 'Continental GTC'),
  ('Cadillac', 'XT5'),
  ('BMW', 'Série 2'),
  ('Rolls-Royce', 'Cullinan'),
  ('Bentley', 'Flying Spur'),
  ('Ford', 'Figo'),
  ('Toyota', 'Sienna'),
  ('Toyota', 'Esquire'),
  ('Toyota', 'Crown'),
  ('Nissan', '370Z'),
  ('Daihatsu', 'Canbus'),
  ('Subaru', 'BRZ'),
  ('Toyota', 'Sienta'),
  ('Honda', 'Spike'),
  ('Suzuki', 'Solio'),
  ('Toyota', 'Alphard quatrième génération'),
  ('Toyota', '40 Vellfire'),
  ('Lexus', 'LC500'),
  ('Subaru', 'STELLA'),
  ('Mitsubishi', 'Delica Mini'),
  ('Toyota', 'Alphard'),
  ('Toyota', 'Corolla Touring Sports'),
  ('Toyota', '86'),
  ('Toyota', 'Aqua'),
  ('Toyota', 'Auris'),
  ('Toyota', 'Prius'),
  ('Toyota', 'Vitz‌'),
  ('Toyota', 'Yaris Cross'),
  ('Toyota', 'Estima'),
  ('Toyota', 'Noah'),
  ('Toyota', 'Passo'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Lexus', 'IS'),
  ('Lexus', 'NX'),
  ('Nissan', 'Note'),
  ('Nissan', 'Serena'),
  ('Subaru', 'Crosstrek'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Impreza'),
  ('Daihatsu', 'Rocky'),
  ('Daihatsu', 'Tanto'),
  ('Honda', 'Fit'),
  ('Honda', 'Step WGN'),
  ('Infiniti', 'Q70'),
  ('Maserati', 'Ghibli'),
  ('Maserati', 'Levante'),
  ('BMW', 'Z4'),
  ('Mazda', 'MX-5'),
  ('Mazda', '2'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'Demio'),
  ('Mazda', 'Biante'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Alto'),
  ('Mercedes-Benz', 'CLS'),
  ('Suzuki', 'Lapin'),
  ('Daihatsu', 'Mira'),
  ('Suzuki', 'Hustler'),
  ('Suzuki', 'Wagon R'),
  ('Honda', 'N-Box'),
  ('Toyota', 'Roomy'),
  ('Nissan', 'Dayz'),
  ('Mitsubishi', 'Delica'),
  ('Honda', 'Freed'),
  ('Daihatsu', 'Move'),
  ('Toyota', 'Corolla Fielder'),
  ('Lexus', 'LS'),
  ('Subaru', 'Levorg'),
  ('Toyota', 'Vellfire'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'Voxy'),
  ('Honda', 'Insight'),
  ('Subaru', 'Outback'),
  ('Toyota', 'Alphard deuxième génération'),
  ('Toyota', 'Alphard troisième génération'),
  ('Toyota', 'Vellfire troisième génération'),
  ('Toyota', 'Vellfire deuxième génération'),
  ('Daihatsu', 'Copen'),
  ('Audi', 'TT'),
  ('Lexus', 'CT'),
  ('Suzuki', 'Spacia'),
  ('Suzuki', 'XBee'),
  ('Toyota', 'Wish'),
  ('Honda', 'Grace'),
  ('Nissan', 'Roox'),
  ('Daihatsu', 'Thor'),
  ('Honda', 'N-WGN'),
  ('Toyota', 'Harrier'),
  ('Toyota', 'Hiace Grand Cabin'),
  ('Toyota', 'Prius III'),
  ('Toyota', 'Prius V'),
  ('MINI', 'One'),
  ('Renault', 'Symbioz'),
  ('Renault', 'Rafale'),
  ('Toyota', 'Aygo'),
  ('Citroën', 'DS3'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Opel', 'Grandland X'),
  ('Fiat', '500C'),
  ('Fiat', '500e'),
  ('Nissan', 'Juke'),
  ('Renault', 'Twingo'),
  ('Renault', 'Espace'),
  ('MINI', 'Cooper'),
  ('Peugeot', '508'),
  ('Peugeot', 'e2008'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'T-Cross'),
  ('Volkswagen', 'Touran'),
  ('Volkswagen', 'Taigo'),
  ('Volkswagen', 'Sharan'),
  ('Renault', 'Talisman'),
  ('Peugeot', '5008'),
  ('Renault', '5'),
  ('Mercedes-Benz', 'GLC Coupé'),
  ('Toyota', 'HIACE'),
  ('BYD', 'Sea Lion 6'),
  ('Honda', 'Fit 2021-2023'),
  ('Lexus', 'LM'),
  ('Mercedes-Benz', 'C180'),
  ('Toyota', 'Voxy (2022-2026)'),
  ('Subaru', 'Levorg Layback'),
  ('Toyota', 'Corolla Axio'),
  ('Nissan', 'Teana'),
  ('Subaru', 'XV'),
  ('Nissan', 'Lafesta'),
  ('Nissan', 'Cima'),
  ('Mazda', 'Premacy'),
  ('Lexus', 'LC'),
  ('Mitsubishi', 'eK'),
  ('Bentley', 'Continental GT'),
  ('Mazda', 'CX-8'),
  ('Mazda', 'MPV'),
  ('BMW', 'Série 2 Active Tourer'),
  ('Toyota', 'Prius IV'),
  ('Subaru', 'Levorg STI'),
  ('Toyota', 'GR Yaris'),
  ('Skoda', 'Elroq'),
  ('Volvo', 'V60'),
  ('Opel', 'Corsa-e'),
  ('BMW', 'Série 5 Touring'),
  ('Skoda', 'Scala'),
  ('Renault', 'Scenic'),
  ('Citroën', 'ë-C3'),
  ('Toyota', 'Corolla Hayon'),
  ('Cupra', 'Formentor')
    )
  ) AS `a_supprimer`
);

-- 2. Suppression des véhicules hors flotte, en excluant ceux qui portent une
--    réservation : ceux-ci sont neutralisés à l'étape 3.
--    promotions et vehicule_prix_entreprises sont en ON DELETE CASCADE.
DELETE `vehicules`
WHERE (`marque`, `modele`) IN (
  ('Toyota', 'Highlander'),
  ('Volvo', '9700'),
  ('Renault', 'Latitude'),
  ('MG', '3'),
  ('Renault', 'Kardian'),
  ('Geely', 'Cityray'),
  ('Peugeot', '108'),
  ('Soueast', 'Soueast S06'),
  ('BYD', 'Song PLUS NEV'),
  ('Fiat', 'Panda'),
  ('Hyundai', 'i20'),
  ('Dacia', 'Jogger'),
  ('Soueast', 'S09'),
  ('Dacia', 'Sandero Stepway'),
  ('Mercedes-Benz', 'GLE'),
  ('Soueast', 'S05'),
  ('Peugeot', '207'),
  ('Opel', 'Corsa'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Proace'),
  ('Citroën', 'Elysée'),
  ('Citroën', 'C4'),
  ('Audi', 'A6'),
  ('Audi', 'Q5'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Elantra'),
  ('Opel', 'Adam'),
  ('Opel', 'Astra'),
  ('Opel', 'Crossland'),
  ('Opel', 'Mokka'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Wrangler'),
  ('Fiat', '500'),
  ('Fiat', '500X'),
  ('Fiat', 'Egea'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Tipo'),
  ('Nissan', 'Qashqai'),
  ('Mercedes-Benz', 'Classe A'),
  ('Mercedes-Benz', 'Classe E'),
  ('Mercedes-Benz', 'Vito'),
  ('SEAT', 'Arona'),
  ('SEAT', 'Leon'),
  ('Chevrolet', 'Spin'),
  ('MG', '5'),
  ('MG', 'HS'),
  ('MG', 'ZS'),
  ('Renault', 'Clio'),
  ('Renault', 'Logan'),
  ('Renault', 'Arkana'),
  ('Renault', 'Captur'),
  ('Renault', 'Mégane'),
  ('Renault', 'Trafic'),
  ('Changan', 'CS35'),
  ('Dacia', 'Sandero'),
  ('Dacia', 'Logan'),
  ('Dacia', 'Logan MCV'),
  ('BMW', 'Série 5'),
  ('BMW', 'X2'),
  ('Cupra', 'Leon'),
  ('Kia', 'Ceed'),
  ('Kia', 'Forte'),
  ('Kia', 'Sportage'),
  ('Kia', 'Sorento'),
  ('Kia', 'Carens'),
  ('Peugeot', '208'),
  ('Peugeot', '2008'),
  ('Peugeot', '3008'),
  ('Peugeot', '301'),
  ('Peugeot', '308'),
  ('Ford', 'Focus'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'T-Roc'),
  ('Skoda', 'Citigo'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Octavia'),
  ('Changan', 'Yuexiang'),
  ('Skoda', 'Superb'),
  ('Dacia', 'Lodgy'),
  ('Geely', 'Emgrand'),
  ('Honda', 'Civic'),
  ('Peugeot', '408'),
  ('Kia', 'K5'),
  ('Kia', 'Carnival'),
  ('Hyundai', 'i30'),
  ('Land', 'Rover Range Rover Evoque'),
  ('Alfa', 'Romeo 159'),
  ('Opel', 'Crossland X'),
  ('Jeep', 'Avenger'),
  ('Mitsubishi', 'Nativa'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Starlet'),
  ('Citroën', 'Picasso'),
  ('Hyundai', 'Getz'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Optra'),
  ('Cadillac', 'STS'),
  ('Citroën', 'C3'),
  ('Nissan', 'Sentra E-Power'),
  ('Trumpchi', 'Emkoo'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Denza', 'D9'),
  ('Exeed', 'Zhuifeng'),
  ('GAC', 'Trumpchi M6'),
  ('Trumpchi', 'GS4'),
  ('Land', 'Rover Range Rover Sport'),
  ('Ford', 'Edge'),
  ('Nissan', 'Xterra'),
  ('Audi', 'R8'),
  ('Volkswagen', 'Polo'),
  ('Porsche', '718 Boxster'),
  ('Rolls-Royce', 'Dawn'),
  ('Chery', 'Omoda'),
  ('Jetour', 'Dasheng'),
  ('Kia', 'K3'),
  ('Toyota', 'LEVIN'),
  ('Trumpchi', 'GS8'),
  ('Tesla', 'Model Y'),
  ('Porsche', 'Cayenne'),
  ('BMW', 'Série 4'),
  ('Porsche', 'Macan'),
  ('Toyota', '4Runner'),
  ('Ford', 'Galaxy'),
  ('Hyundai', 'Venue'),
  ('Honda', 'Odyssey'),
  ('Lamborghini', 'Urus'),
  ('Mercedes-Benz', 'CLE'),
  ('MG', 'GT'),
  ('Trumpchi', 'GS3'),
  ('Mitsubishi', 'Attrage'),
  ('Infiniti', 'QX60'),
  ('Haval', 'H6'),
  ('Geely', 'Boyue L'),
  ('Dongfeng', 'M4U-TOUR'),
  ('Ford', 'Mustang'),
  ('Ford', 'Everest'),
  ('Kia', 'Optima'),
  ('Chery', 'Tiggo'),
  ('Infiniti', 'QX50'),
  ('Chery', 'Tiggo 5X'),
  ('Mitsubishi', 'Xpander'),
  ('Kia', 'Pegas'),
  ('Mercedes-Benz', 'GLA'),
  ('Porsche', 'Panamera'),
  ('Lexus', 'RX'),
  ('Porsche', '911'),
  ('MG', 'RX5'),
  ('Nissan', 'Versa'),
  ('GMC', 'Yukon'),
  ('JAC', 'S3'),
  ('Ford', 'Fusion'),
  ('Land', 'Rover Defender'),
  ('Honda', 'Accord'),
  ('BYD', 'Han'),
  ('Chery', 'Tiggo 7'),
  ('Haval', 'Big Dog'),
  ('Hongqi', 'H5'),
  ('Jeep', 'Grand Cherokee L'),
  ('Mitsubishi', 'ASX'),
  ('Audi', 'RS6'),
  ('JAC', 'JS3'),
  ('Mazda', '3'),
  ('Toyota', 'Raize'),
  ('Hyundai', 'Sonata'),
  ('JAC', 'J7'),
  ('Nissan', 'Sentra'),
  ('Toyota', 'Vios'),
  ('Mazda', '6'),
  ('Dongfeng', 'T5 EVO'),
  ('Chevrolet', 'Groove'),
  ('Bentley', 'Bentayga'),
  ('Chevrolet', 'Spark'),
  ('Lamborghini', 'Huracán'),
  ('Toyota', 'C-HR'),
  ('Geely', 'Boyue PRO'),
  ('Trumpchi', 'GN8'),
  ('Trumpchi', 'GA4'),
  ('Kia', 'Cerato'),
  ('Ford', 'Bronco'),
  ('BYD', 'Qin PLUS'),
  ('Livan', 'X6'),
  ('Polestar', '2'),
  ('MINI', 'Cooper Cabriolet'),
  ('Mercedes-Benz', 'CLA AMG'),
  ('Kia', 'Soluto'),
  ('BMW', 'X7'),
  ('Ford', 'Escort'),
  ('Skywell', 'Auto ET5'),
  ('Toyota', 'Avalon'),
  ('Kaiyi', 'X3 Pro'),
  ('Toyota', 'Yaris Ativ'),
  ('ROX', '01'),
  ('Nissan', 'Magnite'),
  ('Lexus', 'ES'),
  ('Toyota', 'Innova'),
  ('Tesla', 'Model 3'),
  ('Volkswagen', 'Jetta'),
  ('Audi', 'Q8'),
  ('Hyundai', 'Creta'),
  ('SAIC', 'MAXUS G50'),
  ('BMW', 'Série 7'),
  ('Dongfeng', 'Venucia V'),
  ('Toyota', 'Veloz'),
  ('Ford', 'Taurus'),
  ('Hyundai', 'Palisade'),
  ('GAC', 'Trumpchi M8'),
  ('Jeep', 'Cherokee'),
  ('Great', 'Wall Tank 300'),
  ('Nissan', 'Maxima'),
  ('MINI', 'Countryman'),
  ('Chery', 'Arrizo 5'),
  ('Nissan', 'Tiida'),
  ('Chevrolet', 'Corvette'),
  ('Mercedes-Benz', 'GLB'),
  ('Rolls-Royce', 'Wraith'),
  ('Hyundai', 'Stargazer'),
  ('Geely', 'EC7'),
  ('BMW', 'M5'),
  ('Nissan', 'Almera'),
  ('Honda', 'City'),
  ('Honda', 'HR-V'),
  ('Volkswagen', 'Teramont'),
  ('Hongqi', 'HS5'),
  ('Mercedes-Benz', 'GLC'),
  ('Volvo', 'XC40'),
  ('Great', 'Wall Tank 500'),
  ('Ford', 'EcoSport'),
  ('Hongqi', 'EHS9'),
  ('Jeep', 'Compass'),
  ('Ford', 'Fiesta'),
  ('Nissan', 'Sylphy'),
  ('AITO', 'M7'),
  ('Mitsubishi', 'Outlander'),
  ('Suzuki', 'Baleno'),
  ('Mercedes-Benz', 'Classe A AMG'),
  ('Geely', 'GX3 Pro'),
  ('Hongqi', 'H9'),
  ('Venucia', 'Grand V DD-i Super Hybride'),
  ('Chery', 'Tiggo 9'),
  ('Jetour', 'T2'),
  ('Nissan', 'Sunny'),
  ('Infiniti', 'Q50'),
  ('Hongqi', 'HS7'),
  ('Mercedes-Benz', 'CLA'),
  ('Chevrolet', 'Aveo'),
  ('BYD', 'Leopard 5'),
  ('Chevrolet', 'Captiva'),
  ('Nissan', 'Altima'),
  ('Geely', 'HaoYue'),
  ('Jietu', 'X70'),
  ('Geely', 'Xingyue L'),
  ('Zhongxing', 'Lingzhu'),
  ('Audi', 'A3'),
  ('Volvo', 'XC60'),
  ('Citroën', 'C5'),
  ('Hyundai', 'Staria'),
  ('Land', 'Rover Vogue'),
  ('Chery', 'Tiggo 8'),
  ('McLaren', '570S'),
  ('Mazda', '5'),
  ('Bentley', 'Continental GTC'),
  ('Cadillac', 'XT5'),
  ('BMW', 'Série 2'),
  ('Rolls-Royce', 'Cullinan'),
  ('Bentley', 'Flying Spur'),
  ('Ford', 'Figo'),
  ('Toyota', 'Sienna'),
  ('Toyota', 'Esquire'),
  ('Toyota', 'Crown'),
  ('Nissan', '370Z'),
  ('Daihatsu', 'Canbus'),
  ('Subaru', 'BRZ'),
  ('Toyota', 'Sienta'),
  ('Honda', 'Spike'),
  ('Suzuki', 'Solio'),
  ('Toyota', 'Alphard quatrième génération'),
  ('Toyota', '40 Vellfire'),
  ('Lexus', 'LC500'),
  ('Subaru', 'STELLA'),
  ('Mitsubishi', 'Delica Mini'),
  ('Toyota', 'Alphard'),
  ('Toyota', 'Corolla Touring Sports'),
  ('Toyota', '86'),
  ('Toyota', 'Aqua'),
  ('Toyota', 'Auris'),
  ('Toyota', 'Prius'),
  ('Toyota', 'Vitz‌'),
  ('Toyota', 'Yaris Cross'),
  ('Toyota', 'Estima'),
  ('Toyota', 'Noah'),
  ('Toyota', 'Passo'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Lexus', 'IS'),
  ('Lexus', 'NX'),
  ('Nissan', 'Note'),
  ('Nissan', 'Serena'),
  ('Subaru', 'Crosstrek'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Impreza'),
  ('Daihatsu', 'Rocky'),
  ('Daihatsu', 'Tanto'),
  ('Honda', 'Fit'),
  ('Honda', 'Step WGN'),
  ('Infiniti', 'Q70'),
  ('Maserati', 'Ghibli'),
  ('Maserati', 'Levante'),
  ('BMW', 'Z4'),
  ('Mazda', 'MX-5'),
  ('Mazda', '2'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'Demio'),
  ('Mazda', 'Biante'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Alto'),
  ('Mercedes-Benz', 'CLS'),
  ('Suzuki', 'Lapin'),
  ('Daihatsu', 'Mira'),
  ('Suzuki', 'Hustler'),
  ('Suzuki', 'Wagon R'),
  ('Honda', 'N-Box'),
  ('Toyota', 'Roomy'),
  ('Nissan', 'Dayz'),
  ('Mitsubishi', 'Delica'),
  ('Honda', 'Freed'),
  ('Daihatsu', 'Move'),
  ('Toyota', 'Corolla Fielder'),
  ('Lexus', 'LS'),
  ('Subaru', 'Levorg'),
  ('Toyota', 'Vellfire'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'Voxy'),
  ('Honda', 'Insight'),
  ('Subaru', 'Outback'),
  ('Toyota', 'Alphard deuxième génération'),
  ('Toyota', 'Alphard troisième génération'),
  ('Toyota', 'Vellfire troisième génération'),
  ('Toyota', 'Vellfire deuxième génération'),
  ('Daihatsu', 'Copen'),
  ('Audi', 'TT'),
  ('Lexus', 'CT'),
  ('Suzuki', 'Spacia'),
  ('Suzuki', 'XBee'),
  ('Toyota', 'Wish'),
  ('Honda', 'Grace'),
  ('Nissan', 'Roox'),
  ('Daihatsu', 'Thor'),
  ('Honda', 'N-WGN'),
  ('Toyota', 'Harrier'),
  ('Toyota', 'Hiace Grand Cabin'),
  ('Toyota', 'Prius III'),
  ('Toyota', 'Prius V'),
  ('MINI', 'One'),
  ('Renault', 'Symbioz'),
  ('Renault', 'Rafale'),
  ('Toyota', 'Aygo'),
  ('Citroën', 'DS3'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Opel', 'Grandland X'),
  ('Fiat', '500C'),
  ('Fiat', '500e'),
  ('Nissan', 'Juke'),
  ('Renault', 'Twingo'),
  ('Renault', 'Espace'),
  ('MINI', 'Cooper'),
  ('Peugeot', '508'),
  ('Peugeot', 'e2008'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'T-Cross'),
  ('Volkswagen', 'Touran'),
  ('Volkswagen', 'Taigo'),
  ('Volkswagen', 'Sharan'),
  ('Renault', 'Talisman'),
  ('Peugeot', '5008'),
  ('Renault', '5'),
  ('Mercedes-Benz', 'GLC Coupé'),
  ('Toyota', 'HIACE'),
  ('BYD', 'Sea Lion 6'),
  ('Honda', 'Fit 2021-2023'),
  ('Lexus', 'LM'),
  ('Mercedes-Benz', 'C180'),
  ('Toyota', 'Voxy (2022-2026)'),
  ('Subaru', 'Levorg Layback'),
  ('Toyota', 'Corolla Axio'),
  ('Nissan', 'Teana'),
  ('Subaru', 'XV'),
  ('Nissan', 'Lafesta'),
  ('Nissan', 'Cima'),
  ('Mazda', 'Premacy'),
  ('Lexus', 'LC'),
  ('Mitsubishi', 'eK'),
  ('Bentley', 'Continental GT'),
  ('Mazda', 'CX-8'),
  ('Mazda', 'MPV'),
  ('BMW', 'Série 2 Active Tourer'),
  ('Toyota', 'Prius IV'),
  ('Subaru', 'Levorg STI'),
  ('Toyota', 'GR Yaris'),
  ('Skoda', 'Elroq'),
  ('Volvo', 'V60'),
  ('Opel', 'Corsa-e'),
  ('BMW', 'Série 5 Touring'),
  ('Skoda', 'Scala'),
  ('Renault', 'Scenic'),
  ('Citroën', 'ë-C3'),
  ('Toyota', 'Corolla Hayon'),
  ('Cupra', 'Formentor')
)
  AND `id` NOT IN (SELECT `vehicule_id` FROM `reservations`);

-- 3. Véhicules hors flotte encore réservés : retirés de la vente, conservés.
UPDATE `vehicules`
SET `statut` = 'INACTIVE', `disponibilite` = 0, `mis_a_jour_le` = NOW()
WHERE (`marque`, `modele`) IN (
  ('Toyota', 'Highlander'),
  ('Volvo', '9700'),
  ('Renault', 'Latitude'),
  ('MG', '3'),
  ('Renault', 'Kardian'),
  ('Geely', 'Cityray'),
  ('Peugeot', '108'),
  ('Soueast', 'Soueast S06'),
  ('BYD', 'Song PLUS NEV'),
  ('Fiat', 'Panda'),
  ('Hyundai', 'i20'),
  ('Dacia', 'Jogger'),
  ('Soueast', 'S09'),
  ('Dacia', 'Sandero Stepway'),
  ('Mercedes-Benz', 'GLE'),
  ('Soueast', 'S05'),
  ('Peugeot', '207'),
  ('Opel', 'Corsa'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Proace'),
  ('Citroën', 'Elysée'),
  ('Citroën', 'C4'),
  ('Audi', 'A6'),
  ('Audi', 'Q5'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Elantra'),
  ('Opel', 'Adam'),
  ('Opel', 'Astra'),
  ('Opel', 'Crossland'),
  ('Opel', 'Mokka'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Wrangler'),
  ('Fiat', '500'),
  ('Fiat', '500X'),
  ('Fiat', 'Egea'),
  ('Fiat', 'Punto'),
  ('Fiat', 'Tipo'),
  ('Nissan', 'Qashqai'),
  ('Mercedes-Benz', 'Classe A'),
  ('Mercedes-Benz', 'Classe E'),
  ('Mercedes-Benz', 'Vito'),
  ('SEAT', 'Arona'),
  ('SEAT', 'Leon'),
  ('Chevrolet', 'Spin'),
  ('MG', '5'),
  ('MG', 'HS'),
  ('MG', 'ZS'),
  ('Renault', 'Clio'),
  ('Renault', 'Logan'),
  ('Renault', 'Arkana'),
  ('Renault', 'Captur'),
  ('Renault', 'Mégane'),
  ('Renault', 'Trafic'),
  ('Changan', 'CS35'),
  ('Dacia', 'Sandero'),
  ('Dacia', 'Logan'),
  ('Dacia', 'Logan MCV'),
  ('BMW', 'Série 5'),
  ('BMW', 'X2'),
  ('Cupra', 'Leon'),
  ('Kia', 'Ceed'),
  ('Kia', 'Forte'),
  ('Kia', 'Sportage'),
  ('Kia', 'Sorento'),
  ('Kia', 'Carens'),
  ('Peugeot', '208'),
  ('Peugeot', '2008'),
  ('Peugeot', '3008'),
  ('Peugeot', '301'),
  ('Peugeot', '308'),
  ('Ford', 'Focus'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'T-Roc'),
  ('Skoda', 'Citigo'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Octavia'),
  ('Changan', 'Yuexiang'),
  ('Skoda', 'Superb'),
  ('Dacia', 'Lodgy'),
  ('Geely', 'Emgrand'),
  ('Honda', 'Civic'),
  ('Peugeot', '408'),
  ('Kia', 'K5'),
  ('Kia', 'Carnival'),
  ('Hyundai', 'i30'),
  ('Land', 'Rover Range Rover Evoque'),
  ('Alfa', 'Romeo 159'),
  ('Opel', 'Crossland X'),
  ('Jeep', 'Avenger'),
  ('Mitsubishi', 'Nativa'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Starlet'),
  ('Citroën', 'Picasso'),
  ('Hyundai', 'Getz'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Optra'),
  ('Cadillac', 'STS'),
  ('Citroën', 'C3'),
  ('Nissan', 'Sentra E-Power'),
  ('Trumpchi', 'Emkoo'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Denza', 'D9'),
  ('Exeed', 'Zhuifeng'),
  ('GAC', 'Trumpchi M6'),
  ('Trumpchi', 'GS4'),
  ('Land', 'Rover Range Rover Sport'),
  ('Ford', 'Edge'),
  ('Nissan', 'Xterra'),
  ('Audi', 'R8'),
  ('Volkswagen', 'Polo'),
  ('Porsche', '718 Boxster'),
  ('Rolls-Royce', 'Dawn'),
  ('Chery', 'Omoda'),
  ('Jetour', 'Dasheng'),
  ('Kia', 'K3'),
  ('Toyota', 'LEVIN'),
  ('Trumpchi', 'GS8'),
  ('Tesla', 'Model Y'),
  ('Porsche', 'Cayenne'),
  ('BMW', 'Série 4'),
  ('Porsche', 'Macan'),
  ('Toyota', '4Runner'),
  ('Ford', 'Galaxy'),
  ('Hyundai', 'Venue'),
  ('Honda', 'Odyssey'),
  ('Lamborghini', 'Urus'),
  ('Mercedes-Benz', 'CLE'),
  ('MG', 'GT'),
  ('Trumpchi', 'GS3'),
  ('Mitsubishi', 'Attrage'),
  ('Infiniti', 'QX60'),
  ('Haval', 'H6'),
  ('Geely', 'Boyue L'),
  ('Dongfeng', 'M4U-TOUR'),
  ('Ford', 'Mustang'),
  ('Ford', 'Everest'),
  ('Kia', 'Optima'),
  ('Chery', 'Tiggo'),
  ('Infiniti', 'QX50'),
  ('Chery', 'Tiggo 5X'),
  ('Mitsubishi', 'Xpander'),
  ('Kia', 'Pegas'),
  ('Mercedes-Benz', 'GLA'),
  ('Porsche', 'Panamera'),
  ('Lexus', 'RX'),
  ('Porsche', '911'),
  ('MG', 'RX5'),
  ('Nissan', 'Versa'),
  ('GMC', 'Yukon'),
  ('JAC', 'S3'),
  ('Ford', 'Fusion'),
  ('Land', 'Rover Defender'),
  ('Honda', 'Accord'),
  ('BYD', 'Han'),
  ('Chery', 'Tiggo 7'),
  ('Haval', 'Big Dog'),
  ('Hongqi', 'H5'),
  ('Jeep', 'Grand Cherokee L'),
  ('Mitsubishi', 'ASX'),
  ('Audi', 'RS6'),
  ('JAC', 'JS3'),
  ('Mazda', '3'),
  ('Toyota', 'Raize'),
  ('Hyundai', 'Sonata'),
  ('JAC', 'J7'),
  ('Nissan', 'Sentra'),
  ('Toyota', 'Vios'),
  ('Mazda', '6'),
  ('Dongfeng', 'T5 EVO'),
  ('Chevrolet', 'Groove'),
  ('Bentley', 'Bentayga'),
  ('Chevrolet', 'Spark'),
  ('Lamborghini', 'Huracán'),
  ('Toyota', 'C-HR'),
  ('Geely', 'Boyue PRO'),
  ('Trumpchi', 'GN8'),
  ('Trumpchi', 'GA4'),
  ('Kia', 'Cerato'),
  ('Ford', 'Bronco'),
  ('BYD', 'Qin PLUS'),
  ('Livan', 'X6'),
  ('Polestar', '2'),
  ('MINI', 'Cooper Cabriolet'),
  ('Mercedes-Benz', 'CLA AMG'),
  ('Kia', 'Soluto'),
  ('BMW', 'X7'),
  ('Ford', 'Escort'),
  ('Skywell', 'Auto ET5'),
  ('Toyota', 'Avalon'),
  ('Kaiyi', 'X3 Pro'),
  ('Toyota', 'Yaris Ativ'),
  ('ROX', '01'),
  ('Nissan', 'Magnite'),
  ('Lexus', 'ES'),
  ('Toyota', 'Innova'),
  ('Tesla', 'Model 3'),
  ('Volkswagen', 'Jetta'),
  ('Audi', 'Q8'),
  ('Hyundai', 'Creta'),
  ('SAIC', 'MAXUS G50'),
  ('BMW', 'Série 7'),
  ('Dongfeng', 'Venucia V'),
  ('Toyota', 'Veloz'),
  ('Ford', 'Taurus'),
  ('Hyundai', 'Palisade'),
  ('GAC', 'Trumpchi M8'),
  ('Jeep', 'Cherokee'),
  ('Great', 'Wall Tank 300'),
  ('Nissan', 'Maxima'),
  ('MINI', 'Countryman'),
  ('Chery', 'Arrizo 5'),
  ('Nissan', 'Tiida'),
  ('Chevrolet', 'Corvette'),
  ('Mercedes-Benz', 'GLB'),
  ('Rolls-Royce', 'Wraith'),
  ('Hyundai', 'Stargazer'),
  ('Geely', 'EC7'),
  ('BMW', 'M5'),
  ('Nissan', 'Almera'),
  ('Honda', 'City'),
  ('Honda', 'HR-V'),
  ('Volkswagen', 'Teramont'),
  ('Hongqi', 'HS5'),
  ('Mercedes-Benz', 'GLC'),
  ('Volvo', 'XC40'),
  ('Great', 'Wall Tank 500'),
  ('Ford', 'EcoSport'),
  ('Hongqi', 'EHS9'),
  ('Jeep', 'Compass'),
  ('Ford', 'Fiesta'),
  ('Nissan', 'Sylphy'),
  ('AITO', 'M7'),
  ('Mitsubishi', 'Outlander'),
  ('Suzuki', 'Baleno'),
  ('Mercedes-Benz', 'Classe A AMG'),
  ('Geely', 'GX3 Pro'),
  ('Hongqi', 'H9'),
  ('Venucia', 'Grand V DD-i Super Hybride'),
  ('Chery', 'Tiggo 9'),
  ('Jetour', 'T2'),
  ('Nissan', 'Sunny'),
  ('Infiniti', 'Q50'),
  ('Hongqi', 'HS7'),
  ('Mercedes-Benz', 'CLA'),
  ('Chevrolet', 'Aveo'),
  ('BYD', 'Leopard 5'),
  ('Chevrolet', 'Captiva'),
  ('Nissan', 'Altima'),
  ('Geely', 'HaoYue'),
  ('Jietu', 'X70'),
  ('Geely', 'Xingyue L'),
  ('Zhongxing', 'Lingzhu'),
  ('Audi', 'A3'),
  ('Volvo', 'XC60'),
  ('Citroën', 'C5'),
  ('Hyundai', 'Staria'),
  ('Land', 'Rover Vogue'),
  ('Chery', 'Tiggo 8'),
  ('McLaren', '570S'),
  ('Mazda', '5'),
  ('Bentley', 'Continental GTC'),
  ('Cadillac', 'XT5'),
  ('BMW', 'Série 2'),
  ('Rolls-Royce', 'Cullinan'),
  ('Bentley', 'Flying Spur'),
  ('Ford', 'Figo'),
  ('Toyota', 'Sienna'),
  ('Toyota', 'Esquire'),
  ('Toyota', 'Crown'),
  ('Nissan', '370Z'),
  ('Daihatsu', 'Canbus'),
  ('Subaru', 'BRZ'),
  ('Toyota', 'Sienta'),
  ('Honda', 'Spike'),
  ('Suzuki', 'Solio'),
  ('Toyota', 'Alphard quatrième génération'),
  ('Toyota', '40 Vellfire'),
  ('Lexus', 'LC500'),
  ('Subaru', 'STELLA'),
  ('Mitsubishi', 'Delica Mini'),
  ('Toyota', 'Alphard'),
  ('Toyota', 'Corolla Touring Sports'),
  ('Toyota', '86'),
  ('Toyota', 'Aqua'),
  ('Toyota', 'Auris'),
  ('Toyota', 'Prius'),
  ('Toyota', 'Vitz‌'),
  ('Toyota', 'Yaris Cross'),
  ('Toyota', 'Estima'),
  ('Toyota', 'Noah'),
  ('Toyota', 'Passo'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Lexus', 'IS'),
  ('Lexus', 'NX'),
  ('Nissan', 'Note'),
  ('Nissan', 'Serena'),
  ('Subaru', 'Crosstrek'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Impreza'),
  ('Daihatsu', 'Rocky'),
  ('Daihatsu', 'Tanto'),
  ('Honda', 'Fit'),
  ('Honda', 'Step WGN'),
  ('Infiniti', 'Q70'),
  ('Maserati', 'Ghibli'),
  ('Maserati', 'Levante'),
  ('BMW', 'Z4'),
  ('Mazda', 'MX-5'),
  ('Mazda', '2'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'Demio'),
  ('Mazda', 'Biante'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Alto'),
  ('Mercedes-Benz', 'CLS'),
  ('Suzuki', 'Lapin'),
  ('Daihatsu', 'Mira'),
  ('Suzuki', 'Hustler'),
  ('Suzuki', 'Wagon R'),
  ('Honda', 'N-Box'),
  ('Toyota', 'Roomy'),
  ('Nissan', 'Dayz'),
  ('Mitsubishi', 'Delica'),
  ('Honda', 'Freed'),
  ('Daihatsu', 'Move'),
  ('Toyota', 'Corolla Fielder'),
  ('Lexus', 'LS'),
  ('Subaru', 'Levorg'),
  ('Toyota', 'Vellfire'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'Voxy'),
  ('Honda', 'Insight'),
  ('Subaru', 'Outback'),
  ('Toyota', 'Alphard deuxième génération'),
  ('Toyota', 'Alphard troisième génération'),
  ('Toyota', 'Vellfire troisième génération'),
  ('Toyota', 'Vellfire deuxième génération'),
  ('Daihatsu', 'Copen'),
  ('Audi', 'TT'),
  ('Lexus', 'CT'),
  ('Suzuki', 'Spacia'),
  ('Suzuki', 'XBee'),
  ('Toyota', 'Wish'),
  ('Honda', 'Grace'),
  ('Nissan', 'Roox'),
  ('Daihatsu', 'Thor'),
  ('Honda', 'N-WGN'),
  ('Toyota', 'Harrier'),
  ('Toyota', 'Hiace Grand Cabin'),
  ('Toyota', 'Prius III'),
  ('Toyota', 'Prius V'),
  ('MINI', 'One'),
  ('Renault', 'Symbioz'),
  ('Renault', 'Rafale'),
  ('Toyota', 'Aygo'),
  ('Citroën', 'DS3'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Opel', 'Grandland X'),
  ('Fiat', '500C'),
  ('Fiat', '500e'),
  ('Nissan', 'Juke'),
  ('Renault', 'Twingo'),
  ('Renault', 'Espace'),
  ('MINI', 'Cooper'),
  ('Peugeot', '508'),
  ('Peugeot', 'e2008'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'T-Cross'),
  ('Volkswagen', 'Touran'),
  ('Volkswagen', 'Taigo'),
  ('Volkswagen', 'Sharan'),
  ('Renault', 'Talisman'),
  ('Peugeot', '5008'),
  ('Renault', '5'),
  ('Mercedes-Benz', 'GLC Coupé'),
  ('Toyota', 'HIACE'),
  ('BYD', 'Sea Lion 6'),
  ('Honda', 'Fit 2021-2023'),
  ('Lexus', 'LM'),
  ('Mercedes-Benz', 'C180'),
  ('Toyota', 'Voxy (2022-2026)'),
  ('Subaru', 'Levorg Layback'),
  ('Toyota', 'Corolla Axio'),
  ('Nissan', 'Teana'),
  ('Subaru', 'XV'),
  ('Nissan', 'Lafesta'),
  ('Nissan', 'Cima'),
  ('Mazda', 'Premacy'),
  ('Lexus', 'LC'),
  ('Mitsubishi', 'eK'),
  ('Bentley', 'Continental GT'),
  ('Mazda', 'CX-8'),
  ('Mazda', 'MPV'),
  ('BMW', 'Série 2 Active Tourer'),
  ('Toyota', 'Prius IV'),
  ('Subaru', 'Levorg STI'),
  ('Toyota', 'GR Yaris'),
  ('Skoda', 'Elroq'),
  ('Volvo', 'V60'),
  ('Opel', 'Corsa-e'),
  ('BMW', 'Série 5 Touring'),
  ('Skoda', 'Scala'),
  ('Renault', 'Scenic'),
  ('Citroën', 'ë-C3'),
  ('Toyota', 'Corolla Hayon'),
  ('Cupra', 'Formentor')
);

-- 4. La liste du client fait foi : réactivation de la flotte officielle.
UPDATE `vehicules`
SET `statut` = 'ACTIVE', `disponibilite` = 1, `mis_a_jour_le` = NOW()
WHERE `places` NOT IN (25, 32);

-- Contrôle : doit renvoyer uniquement les véhicules de la flotte officielle.
SELECT `marque`, `modele`, `places`
FROM `vehicules`
WHERE `statut` = 'ACTIVE' AND `disponibilite` = 1
ORDER BY `marque`, `modele`;
