# -*- coding: utf-8 -*-
"""
Translations for Section 5: Webography & Detailed Table of Contents
(Paragraphs 641 to 761)
"""

SEC5_TRANS = {
    644: "WEBOGRAPHY",
    645: "REACT.JS. \"Official React 18 Documentation and Virtual DOM\", Meta Open Source. Accessible at: https://react.dev (Accessed August 30, 2026).",
    646: "REACT NATIVE & EXPO. \"Cross-Platform Native Mobile Development with Expo Framework\". Accessible at: https://reactnative.dev and https://docs.expo.dev (Accessed September 15, 2026).",
    647: "BREVO. \"Transactional Email and SMS Delivery API Platform\". Accessible at: https://brevo.com (Accessed September 1, 2026).",
    667: "DETAILED TABLE OF CONTENTS",
    668: "DEDICATION\t - 1 -",
    669: "ACKNOWLEDGEMENTS\t - 2 -",
    670: "FOREWORD\t - 3 -",
    671: "TABLE OF CONTENTS\t - 5 -",
    672: "LIST OF FIGURES\t - 6 -",
    673: "LIST OF TABLES\t - 7 -",
    674: "LIST OF ABBREVIATIONS\t - 8 -",
    675: "ABSTRACT\t - 9 -",
    676: "GENERAL INTRODUCTION\t - 10 -",
    677: "PART I: PROJECT FRAMEWORK AND CONTEXT\t - 11 -",
    678: "Chapter 1: Host Organization Overview\t - 12 -",
    679: "I. Presentation of SOUTARAH GROUP\t - 12 -",
    680: "1. General Presentation\t - 12 -",
    681: "2. Mission, Vision, and Values\t - 12 -",
    682: "3. Business Divisions and Services\t - 13 -",
    683: "4. Strategic Partnerships\t - 14 -",
    684: "Chapter 2: Project Presentation\t - 15 -",
    685: "I. Context and Project Rationale\t - 15 -",
    686: "II. Existing System Diagnosis and Limitations\t - 15 -",
    687: "III. Project Objectives\t - 15 -",
    688: "1. General Objective\t - 15 -",
    689: "2. Specific Objectives\t - 16 -",
    690: "IV. System Specifications\t - 16 -",
    691: "1. Functional Requirements - Client Side\t - 17 -",
    692: "2. Functional Requirements - Administrator Side\t - 16 -",
    693: "3. Technical Requirements and Constraints\t - 17 -",
    694: "V. Task Scheduling and GANTT Diagram\t - 17 -",
    695: "1. Forecast Planning\t - 17 -",
    696: "2. GANTT Schedule Diagram\t - 18 -",
    697: "PART II: CONCEPTUAL STUDY\t - 19 -",
    698: "Chapter 3: Choice of Analysis Methodology\t - 20 -",
    699: "I. Comparative Study of Analysis Methods\t - 20 -",
    700: "II. Application of UP/UML to SOUTARAH GROUP System\t - 21 -",
    701: "1. Use Case Diagrams\t - 21 -",
    702: "❖ Textual Description of Use Cases\t - 22 -",
    703: "2. Activity Diagrams\t - 25 -",
    704: "2.1. Customer Account Creation and Management\t - 25 -",
    705: "2.2. Vehicle Reservation with Availability Verification\t - 27 -",
    706: "2.3. Product Purchase Process\t - 29 -",
    707: "3. Sequence Diagrams\t - 31 -",
    708: "3.1. Secure Online Payment\t - 31 -",
    709: "3.2. Vehicle Reservation\t - 32 -",
    710: "3.3. Product Purchase\t - 33 -",
    711: "3.4. User Registration\t - 34 -",
    712: "4. Class Diagram\t - 35 -",
    713: "PART III: TECHNICAL STUDY\t - 36 -",
    714: "Chapter 4: System Design and Technological Choices\t - 37 -",
    715: "I. Analysis and Justification of Technological Choices\t - 37 -",
    716: "1. Development Environment (IDE)\t - 37 -",
    717: "2. UI/UX Prototyping Tool\t - 38 -",
    718: "3. Web Frontend Technologies\t - 38 -",
    719: "4. Mobile Application Technologies\t - 38 -",
    720: "5. Backend Technologies and REST API\t - 39 -",
    721: "6. Transactional Messaging and Notifications\t - 39 -",
    722: "7. Hosting and Deployment Platform\t - 39 -",
    723: "II. Database Management System (DBMS)\t - 40 -",
    724: "1. Comparison of Major DBMS Engines\t - 40 -",
    725: "2. Choice and Justification of MySQL\t - 41 -",
    726: "III. General System Architecture\t - 41 -",
    727: "PART IV: IMPLEMENTATION AND DEPLOYMENT\t - 43 -",
    728: "Chapter 5: Implementation of Web Platform and Mobile App\t - 44 -",
    729: "I. MySQL Database Implementation\t - 44 -",
    730: "II. Implementation of AI Assistant and Email Notifications (Brevo)\t - 45 -",
    731: "1. Intelligent Virtual Assistant (AI Agent)\t - 45 -",
    732: "2. Messaging and Notification Service (Brevo / SMTP)\t - 45 -",
    733: "III. Implementation of Web Platform Interfaces\t - 46 -",
    734: "1. Home and Authentication Pages\t - 46 -",
    735: "2. Product Catalog\t - 47 -",
    736: "3. Vehicle Reservation Module\t - 48 -",
    737: "4. Multi-Item Shopping Cart and PDF Quote Generation\t - 48 -",
    738: "5. Customer Portal and Request Tracking\t - 49 -",
    739: "IV. Implementation of Mobile Reservation App\t - 49 -",
    740: "1. Home Screen and Detailed Vehicle Sheet\t - 49 -",
    741: "2. Mobile Shopping Cart\t - 50 -",
    742: "V. Implementation of Administrative Back-Office\t - 51 -",
    743: "1. Key Performance Indicator Dashboard\t - 51 -",
    744: "2. Fleet and Reservation Management\t - 51 -",
    745: "Chapter 6: System Deployment\t - 52 -",
    746: "I. Functional Testing and Validation (Acceptance Book)\t - 52 -",
    747: "II. Financial Assessment and Cost Estimation\t - 53 -",
    748: "1. Hardware and Software Costs\t - 53 -",
    749: "2. Annual Hosting and Operational Maintenance Costs\t - 53 -",
    750: "III. Profitability, Return on Investment, and Perspectives\t - 54 -",
    751: "1. Immediate Profitability and Return on Investment (ROI)\t - 54 -",
    752: "2. Platform Evolutionary Perspectives\t - 54 -",
    753: "GENERAL CONCLUSION AND PERSPECTIVES\t - 55 -",
    754: "BIBLIOGRAPHY\t - 56 –",
    755: "I. Academic Reference Books and Course Materials\t - 56 -",
    756: "II. Technical Documentation and Web References\t - 56 -",
    757: "WEBOGRAPHY\t - 57 -",
    758: "DETAILED TABLE OF CONTENTS\t - 58 -"
}
